.TH "user_interface" 3 "Tue Jan 31 2023" "Version 1.0" "GUI for Robot Control using JupyterNotebook" \" -*- nroff -*-
.ad l
.nh
.SH NAME
user_interface
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBmain\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
.. module:: user_interface
   :platform: Unix
   :synopsis: Python module for the user Interface
.. moduleauthor:: SAMIUR RAHMAN

 The user can start and stop using the user interface implemented by this node in the terminal.

Service:
   /user_interface
.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "def user_interface\&.main ()"

.PP
.nf
This function initializes the ROS node and waits for the user to
insert *start* or *stop* to control the robot, by relying on the
`rospy <http://wiki.ros.org/rospy/>`_ module.

The user message is passed to the service``user_interface``,
advertised by :mod:`go_to_point`.
.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for GUI for Robot Control using JupyterNotebook from the source code\&.
